# HTTPS server block - defines virtual host configuration
server {
    
    listen	443 ssl; # Listen on port 443 (HTTPS) for IPv4 connections with SSL enabled
    listen	[::]:443 ssl; # Same for IPv6.

    server_name	$DOMAIN_NAME;

	# Paths to certificates HTTPS (generated dynamically from environment variables):
	ssl_certificate		/etc/nginx/ssl/nginx.crt; # SSL certificate file for domain validation
	ssl_certificate_key	/etc/nginx/ssl/nginx.key; # SSL private key file for encryption

	# Specify supported TLS protocol versions for secure communication
	ssl_protocols		TLSv1.2 TLSv1.3; 

	# Root directory where website files are stored
	root	/var/www/html;
	# Default files to serve when directory is requested (in order)
	index	index.php index.nginx-debian.html;

	# Handle all requests (root location block)
	location / {
		# Try to serve the requested file/directory; if not found, pass to index.php with query string
		try_files $uri $uri/ /index.php$is_args$args;
	}

	# Location block for PHP files=
	location ~ \.php$ {
		
		fastcgi_split_path_info ^(.+\.php)(/.+)$; # Split URI to separate PHP file path from additional path info	
		fastcgi_pass wordpress:9000; # Forward PHP requests to PHP-FPM service running on 'wordpress' container, port 9000
		fastcgi_index index.php; # Specify the index file when a directory is requested
		include fastcgi_params; # Include standard FastCGI parameters		
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name; # Pass the full file path to the PHP script
		fastcgi_param SCRIPT_NAME $fastcgi_script_name; # Pass the requested script name to PHP
	}
# End of server block
}